[package]
name = "starpls_test_util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
starpls_bazel = { path = "../starpls_bazel" }
starpls_syntax = { path = "../starpls_syntax" }
