name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare for build
        run: |
          bazel/setup-ci.sh
          mkdir -p editors/code/dist
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
      - name: Build
        run: bazel build //...
      - name: Run tests
        run: bazel test --build_tests_only //...

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare for build
        run: |
          echo 'import %workspace%/bazel/remote-cache.bazelrc' >>.bazelrc
          echo "build --remote_header=x-buildbuddy-api-key=$BUILDBUDDY_API_KEY" >>.bazelrc
          echo "startup --output_user_root=C:/b" >>.bazelrc
          echo "startup --windows_enable_symlinks" >>.bazelrc
          mkdir -p editors/code/dist
        shell: bash
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
      - name: Build
        run: bazel build //crates/...
      - name: Run tests
        run: bazel test --build_tests_only //crates/...
