name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Prepare for build
      run: |
        cp bazel/remote-cache.bazelrc .bazelrc
        echo "build --remote_header=x-buildbuddy-api-key=$BUILDBUDDY_API_KEY" >> .bazelrc
        mkdir -p editors/code/dist
      env:
        BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
    - name: Build
      run: |
        bazel build //...
        bazel run //editors/code
    - name: Run tests
      run: bazel test //...
